# calculate_distance function rewrite

We will be rewriting the calculate distance function to use properties of NumPy arrays.

In [27]:
import math

import numpy as np

def calculate_distance(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: list
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.

    Returns
    -------
    distance: float
        The distance between the two points.
    """
    distance = 0
    
    for i in range(3):
        dim_dist = (coord1[i] - coord2[i])
        
        if box_length:
            dim_dist = dim_dist - box_length * round(dim_dist / box_length)
            
        dim_dist = dim_dist**2
        distance += dim_dist
        
    distance = math.sqrt(distance)
    return distance

def calculate_distance_np(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    
    Parameters
    ----------
    coord1, coord2 : np.ndarray
        The atomic coordinates

    Returns
    -------
    distance: float
        The distance between the two points.
    """
    
    coord_dist = coord1 - coord2
    
    if box_length:
        coord_dist = coord_dist - box_length * np.round(coord_dist / box_length)
    
    coord_dist = coord_dist ** 2
    
    if coord_dist.ndim < 2:
        coord_dist = coord_dist.reshape(1, -1)
    
    coord_dist_sum = coord_dist.sum(axis=1)
    
    distance = np.sqrt(coord_dist_sum)
    
    return distance

In [28]:
point1 = np.array([0, 0, 0])
point2 = np.array([0, 8, 0])

print(calculate_distance(point1, point2))
print(calculate_distance_np(point1, point2))
print(calculate_distance_np(point1, point2, 10))

8.0
[8.]
[2.]


In [26]:
point1.ndim

1

In [6]:
dimensional_distance = point1 - point2
print(dimensional_distance)

[ 0 -8  0]


In [8]:
dd2 = dimensional_distance ** 2
print(dd2)

[ 0 64  0]


In [10]:
dd2_sum = dd2.sum()
print(dd2_sum)

64


In [12]:
distance = math.sqrt(dd2_sum)
print(distance)

8.0


In [30]:
coord_set1 = np.array([[0, 0, 0], [0, 1, 0]])
coord_set2 = np.array([[0, 8, 0], [0, 1.5, 0]])

calculate_distance_np(coord_set1, coord_set2)

array([8. , 0.5])